from __future__ import annotations

import torch

from configs.predictors.rearranged_transport.amortized_rearranged_transport import (
    AmortizedRearrangedTransportPredictorConfig,
)
from predictors.rearranged_transport.rearranged_transport import (
    RearrangedTransportPredictor,
)
from predictors.transport.base import BaseTransportPredictor


class AmortizedRearrangedTransport(RearrangedTransportPredictor):
    """Coverage-conditioned family of Gaussian-preserving rearrangements.

    For each fixed ``coverage_mass``, the rearrangement is generated by a
    Gaussian-preserving vector field conditioned on ``[x, coverage_mass]``.
    The wrapped transport predictor continues to receive only the original
    covariates ``x``.

    Every rearrangement, transport, and score call requires the intended
    coverage mass explicitly. Conditioning alone does not impose nesting of the
    learned regions as ``coverage_mass`` varies.
    """

    config_class = AmortizedRearrangedTransportPredictorConfig
    coverage_conditioned = True

    def __init__(
        self,
        config: AmortizedRearrangedTransportPredictorConfig,
        transport_predictor: BaseTransportPredictor,
    ):
        if not isinstance(config, AmortizedRearrangedTransportPredictorConfig):
            raise TypeError(
                "config must be an "
                "AmortizedRearrangedTransportPredictorConfig instance."
            )

        super().__init__(
            config=config,
            transport_predictor=transport_predictor,
        )

    def _rearrangement_context_dimension(self) -> int:
        return self.x_dim + 1

    def _prepare_rearrangement_context(
        self,
        x: torch.Tensor,
        coverage_mass: torch.Tensor | float,
    ) -> torch.Tensor:
        x = self.to_device(x)

        if x.ndim == 0 or x.shape[-1] != self.x_dim:
            actual_dimension = None if x.ndim == 0 else x.shape[-1]
            raise ValueError(
                f"Expected x.shape[-1] = {self.x_dim}, got {actual_dimension}."
            )

        coverage_tensor = torch.as_tensor(
            coverage_mass,
            device=x.device,
            dtype=x.dtype,
        )
        batch_shape = x.shape[:-1]

        if coverage_tensor.ndim == 0:
            coverage_tensor = coverage_tensor.expand(*batch_shape, 1)
        else:
            if coverage_tensor.shape == batch_shape:
                coverage_tensor = coverage_tensor.unsqueeze(-1)

            try:
                coverage_tensor = torch.broadcast_to(
                    coverage_tensor,
                    (*batch_shape, 1),
                )
            except RuntimeError as error:
                raise ValueError(
                    "coverage_mass must be scalar or broadcastable to "
                    f"x.shape[:-1] + (1,), got coverage_mass.shape="
                    f"{tuple(coverage_tensor.shape)} and "
                    f"x.shape={tuple(x.shape)}."
                ) from error

        if not torch.isfinite(coverage_tensor).all():
            raise ValueError("coverage_mass must contain only finite values.")

        if not ((coverage_tensor > 0.0) & (coverage_tensor < 1.0)).all():
            raise ValueError("coverage_mass must lie strictly between 0 and 1.")

        return torch.cat([x, coverage_tensor], dim=-1)

    def rearrangement_pushforward(
        self,
        x: torch.Tensor,
        u: torch.Tensor,
        coverage_mass: torch.Tensor | float,
    ) -> torch.Tensor:
        u = self.to_device(u)
        context = self._prepare_rearrangement_context(
            x=x,
            coverage_mass=coverage_mass,
        )
        return self.rearrangement_flow.forward(u=u, x=context)

    def rearrangement_pullback(
        self,
        x: torch.Tensor,
        u: torch.Tensor,
        coverage_mass: torch.Tensor | float,
    ) -> torch.Tensor:
        u = self.to_device(u)
        context = self._prepare_rearrangement_context(
            x=x,
            coverage_mass=coverage_mass,
        )
        return self.rearrangement_flow.inverse(
            u=u,
            x=context,
            start_time=1.0,
        )

    def pushforward(
        self,
        x: torch.Tensor,
        u: torch.Tensor,
        coverage_mass: torch.Tensor | float,
    ) -> torch.Tensor:
        rearranged_u = self.rearrangement_pushforward(
            x=x,
            u=u,
            coverage_mass=coverage_mass,
        )
        return self.transport_pushforward(x=x, u=rearranged_u)

    def pullback(
        self,
        x: torch.Tensor,
        y: torch.Tensor,
        coverage_mass: torch.Tensor | float,
    ) -> torch.Tensor:
        transport_u = self.transport_pullback(x=x, y=y)
        return self.rearrangement_pullback(
            x=x,
            u=transport_u,
            coverage_mass=coverage_mass,
        )

    def log_det(
        self,
        x: torch.Tensor,
        u: torch.Tensor,
        coverage_mass: torch.Tensor | float,
    ) -> torch.Tensor:
        """Return ``log |det D_u (T_x o S_{x, coverage_mass})(u)|``."""
        rearranged_u = self.rearrangement_pushforward(
            x=x,
            u=u,
            coverage_mass=coverage_mass,
        )
        return self.transport_log_det(
            x=x,
            u=rearranged_u,
        ) + self._rearrangement_log_det_from_pushforward(
            u=self.to_device(u),
            rearranged_u=rearranged_u,
        )

    def rearrangement_log_det(
        self,
        x: torch.Tensor,
        u: torch.Tensor,
        coverage_mass: torch.Tensor | float,
    ) -> torch.Tensor:
        rearranged_u = self.rearrangement_pushforward(
            x=x,
            u=u,
            coverage_mass=coverage_mass,
        )
        return self._rearrangement_log_det_from_pushforward(
            u=self.to_device(u),
            rearranged_u=rearranged_u,
        )

    def multivariate_score(
        self,
        x: torch.Tensor,
        y: torch.Tensor,
        coverage_mass: torch.Tensor | float,
    ) -> torch.Tensor:
        return self.pullback(
            x=x,
            y=y,
            coverage_mass=coverage_mass,
        )


AmortizedRearrangedTransportPredictor = AmortizedRearrangedTransport
