from __future__ import annotations

from typing import Any

import torch
import torch.nn as nn
from torchdiffeq import odeint, odeint_adjoint

from networks.measure_preserving_flows.dense_skew_symmetric_vector_field import (
    DenseGaussianSkewVectorField,
)

_FIXED_STEP_METHODS = {"euler", "midpoint", "rk4", "explicit_adams", "implicit_adams"}


class VectorFieldFlow(nn.Module):
    """ODE flow generated by a vector field with signature ``v(u, x, t)``.

    Here u is the integrated variable and x is optional context.

    By default, backpropagation through the ODE solve uses torchdiffeq's adjoint
    method. Set ``use_adjoint=False`` to use regular autograd through ``odeint``.
    """

    def __init__(
        self,
        vector_field: nn.Module,
        endpoint_alpha: float = 0.1,
        alpha: float | None = None,
        use_adjoint: bool = True,
        method: str = "dopri5",
        rtol: float = 1e-5,
        atol: float = 1e-6,
        options: dict[str, Any] | None = None,
        adjoint_method: str | None = None,
        adjoint_rtol: float | None = None,
        adjoint_atol: float | None = None,
        adjoint_options: dict[str, Any] | None = None,
        number_of_steps: int | None = None,
    ):
        super().__init__()

        if alpha is not None:
            endpoint_alpha = alpha

        if number_of_steps is not None and number_of_steps < 1:
            raise ValueError("number_of_steps must be positive when provided.")

        if number_of_steps is not None and method not in _FIXED_STEP_METHODS:
            raise ValueError(
                "number_of_steps is only supported for torchdiffeq fixed-step "
                f"methods: {sorted(_FIXED_STEP_METHODS)}."
            )

        self.vector_field = vector_field

        self.use_adjoint = bool(use_adjoint)
        self.method = method
        self.rtol = float(rtol)
        self.atol = float(atol)
        self.options = {} if options is None else dict(options)
        self.adjoint_method = adjoint_method
        self.adjoint_rtol = adjoint_rtol
        self.adjoint_atol = adjoint_atol
        self.adjoint_options = (
            None if adjoint_options is None else dict(adjoint_options)
        )
        self.number_of_steps = number_of_steps

        self.endpoint_alpha = float(endpoint_alpha)
        self.last_end_time = 1.0

    def _solver_options(
        self,
        start_time: float,
        end_time: float,
        u: torch.Tensor,
    ) -> dict[str, Any]:
        options = dict(self.options)

        if u.device.type == "mps" and self.method not in _FIXED_STEP_METHODS:
            options.setdefault("dtype", u.dtype)

        if self.number_of_steps is not None:
            options.setdefault(
                "step_size",
                abs(end_time - start_time) / self.number_of_steps,
            )

        return options

    def _adjoint_params(self) -> tuple[nn.Parameter, ...]:
        return tuple(self.vector_field.parameters())

    def _prepare_context(
        self,
        u: torch.Tensor,
        x: torch.Tensor | None,
    ) -> torch.Tensor | None:
        if x is None:
            return None

        return x.to(device=u.device, dtype=u.dtype)

    def integrate(
        self,
        u: torch.Tensor,
        x: torch.Tensor | None = None,
        start_time: float = 0.0,
        end_time: float = 1.0,
    ) -> torch.Tensor:
        context = self._prepare_context(u=u, x=x)
        times = u.new_tensor([start_time, end_time])
        solver = odeint_adjoint if self.use_adjoint else odeint
        solver_kwargs: dict[str, Any] = {
            "rtol": self.rtol,
            "atol": self.atol,
            "method": self.method,
            "options": self._solver_options(start_time, end_time, u),
        }

        if self.use_adjoint:
            adjoint_options = (
                None if self.adjoint_options is None else dict(self.adjoint_options)
            )
            adjoint_method = self.adjoint_method or self.method

            if u.device.type == "mps" and adjoint_method not in _FIXED_STEP_METHODS:
                adjoint_options = {} if adjoint_options is None else adjoint_options
                adjoint_options.setdefault("dtype", u.dtype)

            solver_kwargs.update(
                adjoint_method=adjoint_method,
                adjoint_options=adjoint_options,
                adjoint_params=self._adjoint_params(),
            )

            if self.adjoint_rtol is not None:
                solver_kwargs["adjoint_rtol"] = self.adjoint_rtol

            if self.adjoint_atol is not None:
                solver_kwargs["adjoint_atol"] = self.adjoint_atol

        def ode_function(
            t: torch.Tensor,
            state: torch.Tensor,
        ) -> torch.Tensor:
            return self.vector_field(state, context, t)

        solution = solver(
            ode_function,
            u,
            times,
            **solver_kwargs,
        )
        return solution[-1]

    def _sample_end_time(self, u: torch.Tensor) -> float:
        if not self.training or self.endpoint_alpha == 0.0:
            self.last_end_time = 1.0
            return self.last_end_time

        offset = torch.empty((), device=u.device, dtype=u.dtype).uniform_(
            -self.endpoint_alpha,
            self.endpoint_alpha,
        )
        self.last_end_time = float((1.0 + offset).item())
        return self.last_end_time

    def forward(
        self,
        u: torch.Tensor,
        x: torch.Tensor | None = None,
        end_time: float | None = None,
    ) -> torch.Tensor:
        if end_time is None:
            end_time = self._sample_end_time(u)
        else:
            end_time = float(end_time)
            self.last_end_time = end_time

        return self.integrate(u, x=x, start_time=0.0, end_time=end_time)

    def inverse(
        self,
        u: torch.Tensor,
        x: torch.Tensor | None = None,
        start_time: float | None = None,
    ) -> torch.Tensor:
        if start_time is None:
            start_time = self._sample_end_time(u)
        else:
            start_time = float(start_time)
            self.last_end_time = start_time

        return self.integrate(u, x=x, start_time=start_time, end_time=0.0)


class GaussianSkewFieldFlow(VectorFieldFlow):
    """ODE flow generated by ``DenseGaussianSkewVectorField``."""

    def __init__(
        self,
        dimension: int,
        endpoint_alpha: float = 0.1,
        alpha: float | None = None,
        use_adjoint: bool = True,
        method: str = "dopri5",
        rtol: float = 1e-5,
        atol: float = 1e-6,
        options: dict[str, Any] | None = None,
        adjoint_method: str | None = None,
        adjoint_rtol: float | None = None,
        adjoint_atol: float | None = None,
        adjoint_options: dict[str, Any] | None = None,
        number_of_steps: int | None = None,
        context_dimension: int = 0,
        vector_field: DenseGaussianSkewVectorField | None = None,
        **vector_field_kwargs,
    ):
        vector_field = vector_field or DenseGaussianSkewVectorField(
            dimension=dimension,
            context_dimension=context_dimension,
            **vector_field_kwargs,
        )

        super().__init__(
            vector_field=vector_field,
            endpoint_alpha=endpoint_alpha,
            alpha=alpha,
            use_adjoint=use_adjoint,
            method=method,
            rtol=rtol,
            atol=atol,
            options=options,
            adjoint_method=adjoint_method,
            adjoint_rtol=adjoint_rtol,
            adjoint_atol=adjoint_atol,
            adjoint_options=adjoint_options,
            number_of_steps=number_of_steps,
        )
        self.dimension = dimension
        self.context_dimension = context_dimension
