from __future__ import annotations

import math
from typing import Any

import torch
import torch.nn as nn
from torchdiffeq import odeint, odeint_adjoint

from networks.measure_preserving_flows.dense_skew_symmetric_vector_field import (
    DenseGaussianSkewVectorField,
)

_FIXED_STEP_METHODS = {"euler", "midpoint", "rk4", "explicit_adams", "implicit_adams"}
_RANDOM_TIME_GRID_METHODS = {"euler", "midpoint", "rk4"}
_TIME_GRID_JITTER = 0.5


class VectorFieldFlow(nn.Module):
    """ODE flow generated by a vector field with signature ``v(u, x, t)``.

    Here u is the integrated variable and x is optional context.

    When ``number_of_steps`` is set, each solve samples a strictly ordered time
    grid and takes one fixed solver step between every adjacent pair of nodes.

    By default, backpropagation through the ODE solve uses torchdiffeq's adjoint
    method. Set ``use_adjoint=False`` to use regular autograd through ``odeint``.
    """

    def __init__(
        self,
        vector_field: nn.Module,
        endpoint_alpha: float = 0.1,
        alpha: float | None = None,
        use_adjoint: bool = True,
        method: str = "dopri5",
        rtol: float = 1e-5,
        atol: float = 1e-6,
        options: dict[str, Any] | None = None,
        adjoint_method: str | None = None,
        adjoint_rtol: float | None = None,
        adjoint_atol: float | None = None,
        adjoint_options: dict[str, Any] | None = None,
        number_of_steps: int | None = None,
    ):
        super().__init__()

        if alpha is not None:
            endpoint_alpha = alpha

        if number_of_steps is not None and number_of_steps < 1:
            raise ValueError("number_of_steps must be positive when provided.")

        if number_of_steps is not None and method not in _FIXED_STEP_METHODS:
            raise ValueError(
                "number_of_steps is only supported for torchdiffeq fixed-step "
                f"methods: {sorted(_FIXED_STEP_METHODS)}."
            )

        if number_of_steps is not None and method not in _RANDOM_TIME_GRID_METHODS:
            raise ValueError(
                "Random integration time grids are only supported for one-step "
                "torchdiffeq methods: "
                f"{sorted(_RANDOM_TIME_GRID_METHODS)}."
            )

        if number_of_steps is not None:
            for options_name, solver_options in (
                ("options", options),
                ("adjoint_options", adjoint_options),
            ):
                if solver_options is None:
                    continue

                conflicting_options = {
                    "grid_constructor",
                    "step_size",
                }.intersection(solver_options)
                if conflicting_options:
                    raise ValueError(
                        f"{options_name} cannot contain "
                        f"{sorted(conflicting_options)} when number_of_steps is "
                        "set, because the sampled time grid defines every solver "
                        "step."
                    )

        self.vector_field = vector_field

        self.use_adjoint = bool(use_adjoint)
        self.method = method
        self.rtol = float(rtol)
        self.atol = float(atol)
        self.options = {} if options is None else dict(options)
        self.adjoint_method = adjoint_method
        self.adjoint_rtol = adjoint_rtol
        self.adjoint_atol = adjoint_atol
        self.adjoint_options = (
            None if adjoint_options is None else dict(adjoint_options)
        )
        self.number_of_steps = number_of_steps

        self.endpoint_alpha = float(endpoint_alpha)
        self.last_end_time = 1.0
        self.last_time_grid: torch.Tensor | None = None

    def _sample_time_grid(
        self,
        start_time: float,
        end_time: float,
        u: torch.Tensor,
    ) -> torch.Tensor:
        """Return N + 1 ordered nodes defining exactly N solver steps."""
        start_time = float(start_time)
        end_time = float(end_time)

        if not math.isfinite(start_time) or not math.isfinite(end_time):
            raise ValueError("start_time and end_time must be finite.")

        start = u.new_tensor(start_time)
        end = u.new_tensor(end_time)

        if start_time == end_time:
            return start.unsqueeze(0)

        if self.number_of_steps is None:
            return torch.stack((start, end))

        if self.number_of_steps == 1:
            return torch.stack((start, end))

        lower_time = min(start_time, end_time)
        upper_time = max(start_time, end_time)
        lower = u.new_tensor(lower_time)
        upper = u.new_tensor(upper_time)

        interior_indexes = torch.arange(
            1,
            self.number_of_steps,
            device=u.device,
            dtype=u.dtype,
        )
        # Keep every node near its uniform-grid position so random grids cannot
        # contain arbitrarily small or large solver steps.
        jitter = (
            torch.rand(
                self.number_of_steps - 1,
                device=u.device,
                dtype=u.dtype,
            ) - 0.5
        ) * _TIME_GRID_JITTER
        interior_fractions = (interior_indexes + jitter) / self.number_of_steps
        interior_times = lower + (upper - lower) * interior_fractions
        ascending_times = torch.cat(
            (
                lower.unsqueeze(0),
                interior_times,
                upper.unsqueeze(0),
            )
        )

        times = ascending_times if start_time < end_time else ascending_times.flip(0)
        time_differences = times[1:] - times[:-1]
        expected_sign = 1.0 if start_time < end_time else -1.0

        if not bool(torch.all(expected_sign * time_differences > 0).item()):
            raise RuntimeError(
                "The sampled integration times are not strictly monotone in the "
                f"state dtype {u.dtype}. Use fewer steps, a wider time interval, "
                "or a higher-precision dtype."
            )

        return times

    def _solver_options(self, u: torch.Tensor) -> dict[str, Any]:
        options = dict(self.options)

        if u.device.type == "mps" and self.method not in _FIXED_STEP_METHODS:
            options.setdefault("dtype", u.dtype)

        return options

    def _adjoint_params(self) -> tuple[nn.Parameter, ...]:
        return tuple(self.vector_field.parameters())

    def _prepare_context(
        self,
        u: torch.Tensor,
        x: torch.Tensor | None,
    ) -> torch.Tensor | None:
        if x is None:
            return None

        return x.to(device=u.device, dtype=u.dtype)

    def integrate(
        self,
        u: torch.Tensor,
        x: torch.Tensor | None = None,
        start_time: float = 0.0,
        end_time: float = 1.0,
    ) -> torch.Tensor:
        context = self._prepare_context(u=u, x=x)
        times = self._sample_time_grid(
            start_time=start_time,
            end_time=end_time,
            u=u,
        )
        self.last_time_grid = times.detach().clone()

        if times.numel() == 1:
            return u

        solver = odeint_adjoint if self.use_adjoint else odeint
        solver_kwargs: dict[str, Any] = {
            "rtol": self.rtol,
            "atol": self.atol,
            "method": self.method,
            "options": self._solver_options(u),
        }

        if self.use_adjoint:
            adjoint_options = (
                None if self.adjoint_options is None else dict(self.adjoint_options)
            )
            adjoint_method = self.adjoint_method or self.method

            if u.device.type == "mps" and adjoint_method not in _FIXED_STEP_METHODS:
                adjoint_options = {} if adjoint_options is None else adjoint_options
                adjoint_options.setdefault("dtype", u.dtype)

            solver_kwargs.update(
                adjoint_method=adjoint_method,
                adjoint_options=adjoint_options,
                adjoint_params=self._adjoint_params(),
            )

            if self.adjoint_rtol is not None:
                solver_kwargs["adjoint_rtol"] = self.adjoint_rtol

            if self.adjoint_atol is not None:
                solver_kwargs["adjoint_atol"] = self.adjoint_atol

        def ode_function(
            t: torch.Tensor,
            state: torch.Tensor,
        ) -> torch.Tensor:
            return self.vector_field(state, context, t)

        solution = solver(
            ode_function,
            u,
            times,
            **solver_kwargs,
        )
        return solution[-1]

    def _sample_end_time(self, u: torch.Tensor) -> float:
        if not self.training or self.endpoint_alpha == 0.0:
            self.last_end_time = 1.0
            return self.last_end_time

        offset = torch.empty((), device=u.device, dtype=u.dtype).uniform_(
            -self.endpoint_alpha,
            self.endpoint_alpha,
        )
        self.last_end_time = float((1.0 + offset).item())
        return self.last_end_time

    def forward(
        self,
        u: torch.Tensor,
        x: torch.Tensor | None = None,
        end_time: float | None = None,
    ) -> torch.Tensor:
        if end_time is None:
            end_time = self._sample_end_time(u)
        else:
            end_time = float(end_time)
            self.last_end_time = end_time

        return self.integrate(u, x=x, start_time=0.0, end_time=end_time)

    def inverse(
        self,
        u: torch.Tensor,
        x: torch.Tensor | None = None,
        start_time: float | None = None,
    ) -> torch.Tensor:
        if start_time is None:
            start_time = self._sample_end_time(u)
        else:
            start_time = float(start_time)
            self.last_end_time = start_time

        return self.integrate(u, x=x, start_time=start_time, end_time=0.0)


class GaussianSkewFieldFlow(VectorFieldFlow):
    """ODE flow generated by ``DenseGaussianSkewVectorField``."""

    def __init__(
        self,
        dimension: int,
        endpoint_alpha: float = 0.1,
        alpha: float | None = None,
        use_adjoint: bool = True,
        method: str = "dopri5",
        rtol: float = 1e-5,
        atol: float = 1e-6,
        options: dict[str, Any] | None = None,
        adjoint_method: str | None = None,
        adjoint_rtol: float | None = None,
        adjoint_atol: float | None = None,
        adjoint_options: dict[str, Any] | None = None,
        number_of_steps: int | None = None,
        context_dimension: int = 0,
        vector_field: DenseGaussianSkewVectorField | None = None,
        **vector_field_kwargs,
    ):
        vector_field = vector_field or DenseGaussianSkewVectorField(
            dimension=dimension,
            context_dimension=context_dimension,
            **vector_field_kwargs,
        )

        super().__init__(
            vector_field=vector_field,
            endpoint_alpha=endpoint_alpha,
            alpha=alpha,
            use_adjoint=use_adjoint,
            method=method,
            rtol=rtol,
            atol=atol,
            options=options,
            adjoint_method=adjoint_method,
            adjoint_rtol=adjoint_rtol,
            adjoint_atol=adjoint_atol,
            adjoint_options=adjoint_options,
            number_of_steps=number_of_steps,
        )
        self.dimension = dimension
        self.context_dimension = context_dimension
